image : node:alpine

stages :
  - build
  - test

build :
  stage: build 
  script :
    - npm ci --cache .npm --prefer-offline
  cache:
    key: $NODE_MODULES
    paths: 
      - .npm/


test:
  stage: test
  script: 
    - npm test

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  environment:
    name: production
    url: https://example.com
  script:
    - bash deploy/deploy.sh
  only:
    - master


