image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - npm install
  artifacts:
    paths:


test:
  stage: test
  script: 
    - npm test


deploy:
  stage : deploy
  script:
    - cd /home/team22-21


