image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - cd /home
    - ls -lah
    - npm install



test:
  stage: test
  script: 
    - npm test


deploy:
  stage : deploy
  script:
    - cd /home
    - ls
    - npm -i pm2 -g
    - pm2 start npm -- start


