image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - cd /home/team22-21
    - npm install
  artifacts:
    paths:
      - /home/team22-21/node_modules


test:
  stage: test
  script: 
    - npm test


deploy:
  stage : deploy
  script:
    - cd /home/team22-21
    - npm -i pm2 -g
    - pm2 start npm -- start


