image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - cd $CI_PROJECT_DIR
    - npm install
  artifacts:
    paths:
      - $CI_PROJECT_DIR/node_modules


test:
  stage: test
  script: 
    - npm test


deploy:
  stage : deploy
  before_script :
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - ssh-add
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS ufw allow 3000
  script :
    
    - scp -o StrictHostKeyChecking=no $CI_PROJECT_DIR root@$SERVER_IPADDRESS:/home
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS 'cd /home/$CI_PROJECT_DIR;pm2 stop 0;npm install dotenv;pm2 start npm -- start'

