image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - cd $CI_PROJECT_DIR
    - npm install
    - npm install pm2 -g



test:
  stage: test
  script: 
    - cd $CI_PROJECT_DIR
    - npm test


deploy:
  stage : deploy
  script:
    - cd $CI_PROJECT_DIR
    - npm -i pm2
    - pm2 start npm -- start


