image : node:alpine

stages :
  - build
  - test
  - deploy

build :
  stage: build 
  script :
    - npm install


test:
  stage: test
  script: 
    - npm test


deploy:
  stage : deploy
  before_script :
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - ssh-add
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS apt install -y tomcat9
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS ufw allow 8080
  script :
    - ssh root@$SERVER_IP '/home/team22-21; pm2 reload all'


