image : node:alpine

stages :
  - build
  - test
  - deploy
  - e2e
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

.prep :
  before_script:
    - apk add --no-cache python3 py3-pip
    - apk add pkgconfig
    - apk add --no-cache pixman-dev

    - apk add --no-cache build-base 
    - apk add --no-cache g++ 
    - apk add --no-cache cairo-dev 
    - apk add --no-cache jpeg-dev 
    - apk add --no-cache pango-dev 
    - apk add --no-cache giflib-dev

build :

  stage: build 
  extends: 
    - .prep
  script:
    - rm -rf node_modules package-lock.json
    - npm install



  artifacts:
    expire_in: 1h
    paths:
      - node_modules/


test:
  stage: test
  extends: 
    - .prep
  script: 
    - npm test
  cache:
    key: $NODE_MODULES
    paths: 
      - .npm/


deploy:
  stage : deploy
  timeout: 1h
  before_script :
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - ssh-add
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS ufw allow 3000
    - 'apk add --upgrade gettext'
    - 'apk add --upgrade nodejs'
    - envsubst < deploy/env.template > $CI_PROJECT_DIR/.env
  script :
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS 'apt install nodejs;'
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS "test -d /etc/apache2 || (apt update && apt install -y apache2 && systemctl restart apache2 && ufw allow 'Apache Full')"
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS 'test -d /home/project || mkdir /home/project;'
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS 'cd /home/project; rm -r team22-21;'
    - scp -r /builds/mod-team-project-2021/team22-21 root@$SERVER_IPADDRESS:/home/project
    - ssh -o StrictHostKeyChecking=no root@$SERVER_IPADDRESS 'pm2 delete all;cd /home/project/team22-21;rm -r node_modules;npm install;pm2 start npm -- start;docker rm $(docker ps -a -q) || true;'



e2e:
  stage: e2e
  services:
    - selenium/standalone-chrome
  variables:
    SELENIUM_HOST: selenium__standalone-chrome
  script:
    - npm run selenium "/e2e/main.js"
    - npm run selenium "/e2e/title.js"
    - npm run selenium "/e2e/homepage.js"
  artifacts:
    when: always
    paths:
      - tests_output/
    expire_in: 1 hour
